# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20170815_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_img',
            name='img',
            field=models.ImageField(upload_to='gallery_img'),
        ),
    ]
