# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 00:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='poste',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('postID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('poste', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='site',
            fields=[
                ('_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('require', models.BooleanField()),
                ('user_pass', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='static/img/')),
                ('img_c', models.ImageField(null=True, upload_to='static/img/')),
                ('work', models.CharField(max_length=30, null=True)),
                ('hometown', models.CharField(max_length=30, null=True)),
                ('current_town', models.CharField(max_length=30, null=True)),
                ('birth_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('use', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrp.user'),
        ),
        migrations.AddField(
            model_name='poste',
            name='postFrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='scrp.user'),
        ),
        migrations.AddField(
            model_name='poste',
            name='postTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='scrp.user'),
        ),
    ]
