# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-23 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='poste',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('post', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='site',
            fields=[
                ('_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('require', models.BooleanField()),
                ('user_pass', models.CharField(max_length=350)),
                ('pat', models.FileField(upload_to='/home/med/main/patterns')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='static/img/')),
                ('img_c', models.ImageField(null=True, upload_to='static/img/')),
                ('_ids', models.CharField(max_length=30, null=True)),
                ('use', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrp.user'),
        ),
    ]
