# Generated by Django 2.0.3 on 2018-03-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrp', '0002_auto_20180306_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='poste',
            name='postID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
