# Generated by Django 2.0.4 on 2018-04-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrp', '0003_auto_20180306_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poste',
            name='postID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
