# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 00:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='db_site',
            fields=[
                ('Fid', models.AutoField(primary_key=True, serialize=False)),
                ('mypat', models.FileField(upload_to='home/med/main/patterns')),
                ('base_url', models.URLField()),
                ('Uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
