# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_site',
            old_name='pat',
            new_name='mypat',
        ),
    ]
