# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0002_auto_20171119_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_site',
            name='base_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
