# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
